# This is Assignment 11 - Steven Haynes

## Requirement 3

-- In your own words, describe the commonalities and differences between
NumPy arrays and Pandas series.

   A Series in Pandas is similar to an array in NumPy in that a Series is just a one-dimensional array as seen in NumPy, but with added features. A Series uses explicitly defined indices which allows for different data types to be used as the index, whereas a NumPy array index is implicitly defined as an integer. Due to the ability to explicitly define index type, Pandas Series is similar to a regular Python Dictionary, but more efficient.

## Requirement 4

In [2]:
# Create a Pandas series named bill_names with American currency bill denominations as indices (keys) and President
# last names as values. For example: 1 – Washington, 2 – Jefferson, etc.

import numpy as np
import pandas as pd

bill_names = pd.Series(['Washington', 'Jefferson', 'Lincoln', 'Hamilton', 'Jackson', 'Grant', 'McKinley', 'Cleveland', 'Madison'],
                 index=[1, 2, 5, 10, 20, 50, 500, 1000, 5000])

print(bill_names)


1       Washington
2        Jefferson
5          Lincoln
10        Hamilton
20         Jackson
50           Grant
500       McKinley
1000     Cleveland
5000       Madison
dtype: object


## Requirement 5

In [8]:
# . Create a Pandas series-as-dictionary beverages_dict. Make the indices beverage names and comments about the beverage
# as values. For example: ‘Aquafina’: ‘This is my favorite bottled water!’. 

# Creating a Python dictionary
beverages = {'Yoo-hoo': 'A chocolate-flavored beverage.',
                      'Celcius': 'My preferred energy-drink brand.',
                      'Zoa': "An energy drink brand featuring Dwayne 'The Rock' Johnson.",
                      'Water': 'Life in a bottle.',
                      'Fa!rlife': 'Probably the best chocolate milk brand.',
                      'RC Cola': 'Not Coke & not Pepsi.',
                      'Orange Juice': 'Always drink BEFORE brushing your teeth!'}

# Creating the Pandas Series from the Python dictionary
beverages_dict = pd.Series(beverages)
beverages_dict



Yoo-hoo                            A chocolate-flavored beverage.
Celcius                          My preferred energy-drink brand.
Zoa             An energy drink brand featuring Dwayne 'The Ro...
Water                                           Life in a bottle.
Fa!rlife                  Probably the best chocolate milk brand.
RC Cola                                     Not Coke & not Pepsi.
Orange Juice             Always drink BEFORE brushing your teeth!
dtype: object

In [16]:
# Demonstrate accessing:
#    • individual values via the keys
print('Water:', beverages_dict['Water'])
print('RC Cola:', beverages_dict['RC Cola'])
print('\n')

#    • multiple values via slicing
print(beverages_dict['Yoo-hoo': 'Zoa'])


Water: Life in a bottle.
RC Cola: Not Coke & not Pepsi.


Yoo-hoo                       A chocolate-flavored beverage.
Celcius                     My preferred energy-drink brand.
Zoa        An energy drink brand featuring Dwayne 'The Ro...
dtype: object


## Requirement 6

In [40]:
# Obtain the real city proper population data for the following cities:
# Chongquing, Shanghai, Tokyo, Moscow, Mexico City, London, & New York.
# Create a series-as-dictionary named population based on this information.

population = pd.Series({'Chongquing': 16874740, 'Shanghai': 28516904, 'Tokyo': 37274000, 'Moscow': 12640818,
                        'Mexico City': 22085140, 'London': 9540576, 'New York': 8930002})

# Population data from: https://worldpopulationreview.com/world-cities
print(population)

Chongquing     16874740
Shanghai       28516904
Tokyo          37274000
Moscow         12640818
Mexico City    22085140
London          9540576
New York        8930002
dtype: int64


## Requirement 7

In [41]:
# Create a Pandas series-as-dictionary named city_country with the cities in population and the countries for each city.

city_country = pd.Series({'Chongquing': 'China', 'Shanghai': 'China', 'Tokyo': 'Japan', 'Moscow': 'Russia',
                          'Mexico City': 'Mexico', 'London': 'United Kingdom', 'New York': 'United States'})

print(city_country)


Chongquing              China
Shanghai                China
Tokyo                   Japan
Moscow                 Russia
Mexico City            Mexico
London         United Kingdom
New York        United States
dtype: object


## Requirement 8

In [42]:
# Create a Pandas dataframe object named city_dataframe from a dictionary of series objects using population and city_country.

city_dataframe = pd.DataFrame({'Population': population,
                       'Country': city_country})

print(city_dataframe)


             Population         Country
Chongquing     16874740           China
Shanghai       28516904           China
Tokyo          37274000           Japan
Moscow         12640818          Russia
Mexico City    22085140          Mexico
London          9540576  United Kingdom
New York        8930002   United States


In [44]:
# Show:
#    • the .index property

city_dataframe.index




Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')

In [45]:
# Show:
#    • the .columns property

city_dataframe.columns


Index(['Population', 'Country'], dtype='object')

In [46]:
# Show:
#    • the .keys() method

city_dataframe['Country']


Chongquing              China
Shanghai                China
Tokyo                   Japan
Moscow                 Russia
Mexico City            Mexico
London         United Kingdom
New York        United States
Name: Country, dtype: object

## Requirement 9

In [24]:
# Create a Pandas series object named my_pd_series from a collection of string keys and collection of numeric values
# of your choosing. 

my_pd_series = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})

print(my_pd_series)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [33]:
# Demonstrate:
#    • modifying a value based on key
my_pd_series['b'] = 7
print(my_pd_series)
print('\n')

#    • slicing by explicit index
print(my_pd_series['c': 'e'])
print('\n')

#    • slicing by implicit integer index
print(my_pd_series[1:3])
print('\n')

#    • masking
print(my_pd_series[(my_pd_series > 3) & (my_pd_series < 7)])
print('\n')

#    • fancy indexing
print(my_pd_series[['b', 'd']])
print('\n')

#    • loc[]
print('Explicit: ', my_pd_series.loc['b'])
print('\n')

#    • iloc[]
print('Implicit: ', my_pd_series.iloc[2])


a    1
b    7
c    3
d    4
e    5
dtype: int64


c    3
d    4
e    5
dtype: int64


b    7
c    3
dtype: int64


d    4
e    5
dtype: int64


b    7
d    4
dtype: int64


Explicit:  7


Implicit:  3


## Requirement 10

In [47]:
# Using city_dataframe, demonstrate:
#   • access column via dictionary-style indexing of the column name
print(city_dataframe['Population'])
print('\n')

#   • access column via column names that are strings
print(city_dataframe.Population)
print('\n')
     
#   • add a new column to the city_dataframe named altitude. 
city_dataframe['Altitude'] = 'currently unknown'
print(city_dataframe)


Chongquing     16874740
Shanghai       28516904
Tokyo          37274000
Moscow         12640818
Mexico City    22085140
London          9540576
New York        8930002
Name: Population, dtype: int64


Chongquing     16874740
Shanghai       28516904
Tokyo          37274000
Moscow         12640818
Mexico City    22085140
London          9540576
New York        8930002
Name: Population, dtype: int64


             Population         Country           Altitude
Chongquing     16874740           China  currently unknown
Shanghai       28516904           China  currently unknown
Tokyo          37274000           Japan  currently unknown
Moscow         12640818          Russia  currently unknown
Mexico City    22085140          Mexico  currently unknown
London          9540576  United Kingdom  currently unknown
New York        8930002   United States  currently unknown


## Requirement 11

In [49]:
# Create two Pandas series that when added using ‘+’ produce some NaN entries.

A = pd.Series([7, 14, 21], index=[0, 1, 2])
B = pd.Series([6, 12, 18], index=[2, 3, 4])

print(A + B)
print('\n')

# Use the .add() method and a fill_value to replace the NaN entries.
print(A.add(B, fill_value=11))


0     NaN
1     NaN
2    27.0
3     NaN
4     NaN
dtype: float64


0    18.0
1    25.0
2    27.0
3    23.0
4    29.0
dtype: float64


## Requirement 12

In [56]:
# Create two Pandas dataframes that when added using ‘+’ produce some NaN entries.

X = pd.DataFrame(np.random.randint(5, 35, (2, 2)),
                 columns=list('AB'))

Y = pd.DataFrame(np.random.randint(0, 50, (4, 4)),
                 columns=list('BACD'))

print(X+Y)
print('\n')

# Use the .add() method and a fill_value of the mean of one of the dataframes to replace the NaN entries.

print(X.add(Y, fill_value=X.stack().mean()))


      A     B   C   D
0  70.0  38.0 NaN NaN
1  43.0  48.0 NaN NaN
2   NaN   NaN NaN NaN
3   NaN   NaN NaN NaN


       A      B      C      D
0  70.00  38.00  65.25  35.25
1  43.00  48.00  48.25  36.25
2  25.25  38.25  41.25  39.25
3  34.25  27.25  72.25  62.25


## Requirement 13

In [63]:
# Create a two-dimensional NumPy array using:
# A = rng.randint(5, 10, size=(4, 4))

rng = np.random.RandomState(42)
A = rng.randint(5, 10, size=(4,4))
print(A)
print('\n')

# Demonstrate: subtracting row 0 of A from A

print(A - A[0])


[[8 9 7 9]
 [9 6 7 7]
 [7 9 8 7]
 [9 6 8 6]]


[[ 0  0  0  0]
 [ 1 -3  0 -2]
 [-1  0  1 -2]
 [ 1 -3  1 -3]]


## Requirement 14

In [64]:
# Create a Pandas dataframe using:
# df = pd.DataFrame(A, columns=list('QRST'))

df = pd.DataFrame(A, columns=list('QRST'))
print(df)
print('\n')

# Demonstrate: subtracting row 1 of df from df using df.iloc[1]

print(df - df.iloc[1])


   Q  R  S  T
0  8  9  7  9
1  9  6  7  7
2  7  9  8  7
3  9  6  8  6


   Q  R  S  T
0 -1  3  0  2
1  0  0  0  0
2 -2  3  1  0
3  0  0  1 -1


## Requirement 15

Compare and contrast the two sentinel values Pandas uses to represent missing data.

-- You can use a global convention or a data-specific convention to represent missing data in Pandas. With a global convention (like NaN), it may not be available for your specific data-type. A data-specific convention (like -99999), you have reduced the range of available return values. Additionally, depending on your return values you sentinel may be harder to distinguish from actual valid values.


## Requirement 16

In [69]:
# Demonstrate the %timeit difference between operations using Python objects and Python integers.

value1 = np.array([5, None, 1, 477])

for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()
    

dtype = object
49.1 ms ± 1.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
1.85 ms ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



## Requirement 17

In [74]:
# Create a Pandas series containing null data. Use .isnull() to identify the entries that are null.

null_data = pd.Series([5, 7, 'a', np.nan, 'beans', 32, 15, None])
print(null_data)
print('\n')
print(null_data.isnull())


0        5
1        7
2        a
3      NaN
4    beans
5       32
6       15
7     None
dtype: object


0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
dtype: bool


## Requirement 18

In [134]:
# Create a Pandas dataframe containing null values. 

null_df = pd.DataFrame([[16,      np.nan,  'a'],
                       [57.2,      7,        5],
                       [np.nan,   'r',       2]])
print(null_df)




      0    1  2
0  16.0  NaN  a
1  57.2    7  5
2   NaN    r  2


In [135]:
# Demonstrate:
#    • drop all rows containing a null value
print(null_df.dropna())
print('\n')

#    • drop all columns containing a null value
print(null_df.dropna(axis= 1))
print('\n')



      0  1  2
1  57.2  7  5


   2
0  a
1  5
2  2




In [140]:
# Demonstrate:
#    • drop only rows that contain all null values

null_row_df = pd.DataFrame([[np.nan, np.nan, np.nan], # Create an all null row DataFrame
                           [1, 2, 3],
                           ['a', 'b', 'c']]) 
print(null_row_df)


print(null_row_df.dropna(axis='rows', how='all')) # Dropping the all null row



     0    1    2
0  NaN  NaN  NaN
1    1    2    3
2    a    b    c
   0  1  2
1  1  2  3
2  a  b  c


In [145]:
# Demonstrate:
#    • drop only columns that contain all null values

null_df[3] = np.nan # Creating an all null column
print('New null column: ', '\n', null_df, '\n')


print('Dropped null column: ', '\n', null_df.dropna(axis='columns', how='all')) # Dropping the all null column
print('\n')


New null column:  
       0    1  2   3
0  16.0  NaN  a NaN
1  57.2    7  5 NaN
2   NaN    r  2 NaN 

Dropped null column:  
       0    1  2
0  16.0  NaN  a
1  57.2    7  5
2   NaN    r  2




In [146]:
# Demonstrate:
#    • replacing null with 0

print('null with zeros: ', '\n', null_df.fillna(0))
print('\n')

#    • forward fill
print('forward fill: ', '\n', null_df.fillna(method='ffill'))
print('\n')

#    • backward fill 
print('backward fill: ', '\n', null_df.fillna(method='bfill'))


null with zeros:  
       0  1  2    3
0  16.0  0  a  0.0
1  57.2  7  5  0.0
2   0.0  r  2  0.0


forward fill:  
       0    1  2   3
0  16.0  NaN  a NaN
1  57.2    7  5 NaN
2  57.2    r  2 NaN


backward fill:  
       0  1  2   3
0  16.0  7  a NaN
1  57.2  7  5 NaN
2   NaN  r  2 NaN


## Requirement 19

In [202]:
# Demonstrate Pandas MultiIndex techniques (can use book examples):
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop


(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [203]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [204]:
#    • .from_tuples()

index = pd.MultiIndex.from_tuples(index)
index


MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [205]:
#    • .reindex()
pop = pop.reindex(index)
pop
      

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [206]:
#    .unstack()
pop_df = pop.unstack()
pop_df


2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [207]:
#    • .stack()
pop_df.stack()


California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [210]:
#    • slicing
pop[:, 2010]


California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [213]:
#    • and indexing
pop[1]


37253956

## Requirement 20

In [217]:
# Demonstrate concatenating two Pandas series. One series contains automobile data. The other series contains motorcycle data.

cars = pd.Series(['Acura', 'Bentley', 'Cadillac'])
bikes = pd.Series(['Ducati', 'Evoke', 'Fantic'])
pd.concat([cars, bikes], ignore_index= True)


0       Acura
1     Bentley
2    Cadillac
3      Ducati
4       Evoke
5      Fantic
dtype: object

## Requirement 21

In [218]:
# Demonstrate concatenating two Pandas dataframe using the .append() method.

print(null_df.append(null_row_df))


      0    1    2   3
0  16.0  NaN    a NaN
1  57.2    7    5 NaN
2   NaN    r    2 NaN
0   NaN  NaN  NaN NaN
1     1    2    3 NaN
2     a    b    c NaN


C:\Users\Steve\AppData\Local\Temp\ipykernel_20820\3321661666.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(null_df.append(null_row_df))


## Requirement 22

In [257]:
# Using Pandas dataframes, demonstrate the following joins:

# Create a few DataFrames to use.
df76 = pd.DataFrame({'Athlete': ['Angel', 'Corina', 'Molly', 'Maggie', 'Kailee', 'Morgan'],
                    'Team': ['WWP', 'WWP', 'WWP', 'SWIM', 'SWIM', 'WWP']})
df77 = pd.DataFrame({'Athlete': ['Angel', 'Corina', 'Molly', 'Maggie', 'Kailee', 'Morgan'],
                    'Squat': [225, 315, 275, 255, 155, 245]})

display(df76, df77)


Athlete  Team
0   Angel   WWP
1  Corina   WWP
2   Molly   WWP
3  Maggie  SWIM
4  Kailee  SWIM
5  Morgan   WWP

Athlete  Squat
0   Angel    225
1  Corina    315
2   Molly    275
3  Maggie    255
4  Kailee    155
5  Morgan    245

In [266]:
#    • one-to-one
df86 = pd.merge(df76, df77)

display(df76, df77)
display(df86)


Athlete  Team
0   Angel   WWP
1  Corina   WWP
2   Molly   WWP
3  Maggie  SWIM
4  Kailee  SWIM
5  Morgan   WWP

Athlete  Squat
0   Angel    225
1  Corina    315
2   Molly    275
3  Maggie    255
4  Kailee    155
5  Morgan    245

Athlete  Team  Squat
0   Angel   WWP    225
1  Corina   WWP    315
2   Molly   WWP    275
3  Maggie  SWIM    255
4  Kailee  SWIM    155
5  Morgan   WWP    245

In [265]:
#    • many-to-one

df78 = pd.DataFrame({'Team': ['WWP', 'SWIM'],
                    'Coach': ['Arredondo', 'Hall']})


display(df78, df86)
display(pd.merge(df86, df78))


Team      Coach
0   WWP  Arredondo
1  SWIM       Hall

Athlete  Team  Squat
0   Angel   WWP    225
1  Corina   WWP    315
2   Molly   WWP    275
3  Maggie  SWIM    255
4  Kailee  SWIM    155
5  Morgan   WWP    245

Athlete  Team  Squat      Coach
0   Angel   WWP    225  Arredondo
1  Corina   WWP    315  Arredondo
2   Molly   WWP    275  Arredondo
3  Morgan   WWP    245  Arredondo
4  Maggie  SWIM    255       Hall
5  Kailee  SWIM    155       Hall

In [267]:
#    • many-to-many
df79 = pd.DataFrame({'Team': ['SWIM', 'WWP',
                              'WWP', 'WWP'],
                    'Equipment': ['Pool', 'Pool', 'Ball', 'Net']})

display(df76, df79)
display(pd.merge(df76, df79))


Athlete  Team
0   Angel   WWP
1  Corina   WWP
2   Molly   WWP
3  Maggie  SWIM
4  Kailee  SWIM
5  Morgan   WWP

Team Equipment
0  SWIM      Pool
1   WWP      Pool
2   WWP      Ball
3   WWP       Net

Athlete  Team Equipment
0    Angel   WWP      Pool
1    Angel   WWP      Ball
2    Angel   WWP       Net
3   Corina   WWP      Pool
4   Corina   WWP      Ball
5   Corina   WWP       Net
6    Molly   WWP      Pool
7    Molly   WWP      Ball
8    Molly   WWP       Net
9   Morgan   WWP      Pool
10  Morgan   WWP      Ball
11  Morgan   WWP       Net
12  Maggie  SWIM      Pool
13  Kailee  SWIM      Pool

## Requirement 23

In [271]:
# Using Pandas dataframes, demonstrate merge with the following keywords:
#    • on

display(df78, df79)
display(pd.merge(df78, df79, on= 'Team'))


Team      Coach
0   WWP  Arredondo
1  SWIM       Hall

Team Equipment
0  SWIM      Pool
1   WWP      Pool
2   WWP      Ball
3   WWP       Net

Team      Coach Equipment
0   WWP  Arredondo      Pool
1   WWP  Arredondo      Ball
2   WWP  Arredondo       Net
3  SWIM       Hall      Pool

In [274]:
#    • left_on and right_on

df75 = pd.DataFrame({'Name': ['Angel', 'Corina', 'Molly', 'Maggie', 'Kailee', 'Morgan'],
                    'Bench': [95, 185, 155, 155, 95, 115]})
display(df77, df75)
display(pd.merge(df77, df75, left_on= 'Athlete', right_on= 'Name'))


Athlete  Squat
0   Angel    225
1  Corina    315
2   Molly    275
3  Maggie    255
4  Kailee    155
5  Morgan    245

Name  Bench
0   Angel     95
1  Corina    185
2   Molly    155
3  Maggie    155
4  Kailee     95
5  Morgan    115

Athlete  Squat    Name  Bench
0   Angel    225   Angel     95
1  Corina    315  Corina    185
2   Molly    275   Molly    155
3  Maggie    255  Maggie    155
4  Kailee    155  Kailee     95
5  Morgan    245  Morgan    115

In [279]:
#    • left_index and right_index

df77b = df77.set_index('Athlete')

df75b = pd.DataFrame({'Athlete': ['Angel', 'Corina', 'Molly', 'Maggie', 'Kailee', 'Morgan'],
                    'Bench': [95, 185, 155, 155, 95, 115]})
df75c= df75b.set_index('Athlete')

display(df77b, df75c, pd.merge(df77b, df75c, left_index= True, right_index= True))


Squat
Athlete       
Angel      225
Corina     315
Molly      275
Maggie     255
Kailee     155
Morgan     245

Bench
Athlete       
Angel       95
Corina     185
Molly      155
Maggie     155
Kailee      95
Morgan     115

Squat  Bench
Athlete              
Angel      225     95
Corina     315    185
Molly      275    155
Maggie     255    155
Kailee     155     95
Morgan     245    115

## Requirement 24

--Use markdown to include a statement at the end of assignment-11.ipynb
explaining your experiences with Assignment 11. Make this authentic
(minimum of 2-3 sentences).

I ran into trouble in Requirement 18 when trying to create an all null row in an existing DataFrame. I couldn't figure out a simple method, and ended up just creating a whole new DataFrame. I know you can add a column easily, and did so. *Stack Overflow has an answer that I just found using .loc().* Requirement 19 was frustrating for me as well. I tried to create my own examples using census data for local cities/towns, but never got the levels to return in the OUT file... I ended up using the book examples, and still did not get the levels to return.

I additionally learned to pay more attention to letter case, as I threw a few errors due to not paying attention to Swim vs SWIM.

Overall, I like Pandas... I know why Data Science job postings want familiarity with Pandas, as Pandas is more convenient than SQL in my opinion.